package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cartwright</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:700px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.item{background:var(--bg2);border:1px solid var(--bg3);padding:.6rem;margin-bottom:.3rem}.item h3{font-size:.82rem;margin-bottom:.15rem}.item-meta{font-size:.65rem;color:var(--cm);display:flex;gap:.5rem;flex-wrap:wrap}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:500px;max-height:90vh;overflow-y:auto}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=number]{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}.del{color:var(--cm);cursor:pointer;font-size:.65rem;float:right}.del:hover{color:var(--rust)}</style></head>
<body><div class="hdr"><h1><span>Stockyard</span> Cartwright</h1><button class="btn btn-p" onclick="showModal()">+ New</button></div>
<div class="main" id="list"></div>
<div class="modal-bg" id="modal" style="display:none" onclick="if(event.target===this)hideModal()"><div class="modal"><h2>New Report</h2>
<label class="fl">Title</label><input type="text" id="f-title" placeholder="Title"><label class="fl">Description</label><input type="text" id="f-description" placeholder="Description"><label class="fl">Query</label><input type="text" id="f-query" placeholder="Query"><label class="fl">Chart Type</label><input type="text" id="f-chart_type" placeholder="Chart Type"><label class="fl">Data Source</label><input type="text" id="f-data_source" placeholder="Data Source"><label class="fl">Schedule</label><input type="text" id="f-schedule" placeholder="Schedule"><label class="fl">Last Run At</label><input type="text" id="f-last_run_at" placeholder="Last Run At">
<div style="margin-top:1rem;display:flex;gap:.5rem"><button class="btn btn-p" onclick="save()">Save</button><button class="btn" style="color:var(--cm);border-color:var(--bg3)" onclick="hideModal()">Cancel</button></div></div></div>
<script>
const API="/api/reports";
function showModal(){document.getElementById("modal").style.display="flex"}
function hideModal(){document.getElementById("modal").style.display="none"}
async function load(){const r=await fetch(API);const d=await r.json();const el=document.getElementById("list");if(!d.reports||!d.reports.length){el.innerHTML='<div class="empty">No reports yet</div>';return}
el.innerHTML=d.reports.map(e=>'<div class="item"><span class="del" onclick="del(\'{}'.replace('{}',e.id)+'\')">[x]</span><h3>${e.title}</h3><div class="item-meta"><span>${e.description||"—"}</span><span>${e.query||"—"}</span><span>${e.chart_type||"—"}</span><span>${e.data_source||"—"}</span></div></div>').join("")}
async function save(){const body={"title":document.getElementById("f-title").value,"description":document.getElementById("f-description").value,"query":document.getElementById("f-query").value,"chart_type":document.getElementById("f-chart_type").value,"data_source":document.getElementById("f-data_source").value,"schedule":document.getElementById("f-schedule").value,"last_run_at":document.getElementById("f-last_run_at").value};await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});hideModal();load()}
async function del(id){await fetch(API+"/"+id,{method:"DELETE"});load()}
load()
</script></body></html>` 